package com.brancucci.ramblinwrecks.search;

public enum VehicleColors {
    ALUMINUM, BEIGE, BLACK, BLUE, BROWN, BRONZE, CLARET, COPPER, CREAM, GOLD, GRAY, GREEN, MAROON, METALLIC, NAVY,
    ORANGE, PINK, PURPLE, RED, ROSE, RUST, SILVER, TAN, TURQUOISE, WHITE, YELLOW

}
